### ISSUE TITLE
Alarms stay in a single timezone

### ISSUE THREAD

**Issue by jsquyres** [reini1305/alarmsplusplus#3]
Greetings, and many thanks for Alarms++!  I've been using it and am very happy with it.

I just took a business trip to a different timezone, and noticed that the alarm I have set in Alarms++ is still reflecting the timezone of where I set it -- not the timezone that I am in.

Specifically, I have a wakeup alarm set for 6am. I created this alarm when I was home -- in the US Eastern time zone.  However, I am currently in the US Pacific time zone -- -3 hours from US Eastern time.  The alarm went off this morning at 6am US _Eastern_ time (i.e., 3am US Pacific time).  Meaning: the alarm seems to be "pinned" to _US Eastern time_, not "6am in the current timezone".

A few more data points:
- My phone switched timezone when I arrived here, and therefore so did my Pebble.  Meaning: both my iPhone and Pebble are reflecting the correct local time (in the US Pacific timezone).
- When I go into Pebble->Settings->Alarms++, it shows that the alarm is set for 6am -- it does not indicate a timezone.

Is this intentional behavior?

If so, would it be possible to add a toggle (either globally or on each alarm) to differentiate between:
- Trigger this alarm at time X in the timezone in which the alarm was created
- Trigger this alarm at time X in the local timezone

FWIW/as a random comparison point: alarms set in the default iOS Clock app are treated as "time X in the current timezone."  I.e., if I set an alarm for 6am while in the US Eastern timezone, but then travel to a different timezone, the alarm will go off at 6am _local time_ (not 6am US Eastern time).

Thank you!

**Comment by reini1305** [comment]
Hi!

Thank you for your detailed report. The main issue with timezones on Pebble is, that the OS doesn't know about them, which in turn means that I can't handle them properly. Regarding your problem of "pinned" alarms: I guess this can be fixed by first setting the clock to the new timezone, and then opening and closing Alarms++. Upon closing of the app, the alarms are reprogrammed according to the current time.

Until Pebble OS informs programs about a timezone change this is the only workaround I can think about.

Best,
Christian

**Comment by jsquyres** [comment]
Ah, yes, if Pebble OS doesn't tell you about timezones, there really isn't much you can do.  Bummer!

I'm not involved with the Pebble OS developer community -- are there any open requests to Pebble to support timezones?

Random thought: what happens when my iPhone updates its time (e.g., when I switch out of airplane mode and it switches to the local timezone)?  I see that my Pebble updates its time to match -- is there any meta information sent in that data exchange that could be utilized to realize that a timezone change occurred (vs. a routine time adjustment)?

I'm guessing "no", because even if there is such meta information, I'm guessing that it isn't made available to watch faces/apps...?

**Comment by jsquyres** [comment]
Another random thought (please feel free to tell me that this is silly/nonsensical...!):

Does Pebble OS tell you when there's a time adjustment (of any kind)?  I.e., if the Pebble adjusts time, can you de-program/re-program all the alarms?

I say this because I'm inferring from your comment that when Alarms++ programs an alarm (i.e., at 6am in US Eastern time), the alarm is set to a fixed time X that doesn't change when the Pebble adjusts its time in reaction to the paired phone changing its time.

But if Alarms++ can be notified when the Pebble OS adjusts it time -- for any reason -- then it could re-program the currently-set alarms (or perhaps re-program them only if the newly-computed time-to-fire Y is different than the previously-computed time-to-fire X?).  This would effectively adjust for timezone changes without needing to know about timezones.

Is that possible, or am I off the deep end here?

**Comment by Dazby** [comment]
When the iphone updates, the pebble app (on the phone) _should_ update the time on the watch. The problem then is trying to get the pebble to run the app and update the alarm times. I wonder if there a way to latch on to this call...

You could add a listener that's called with the HOUR TimeUnit changes but off-hand I can't think how you would differentiate the listener running because 60 minutes has passed or the timezone has changed. The struct_tm doesn't have a timezone field and I'm the watch itself only keeps track of time and not timezone (i.e. it only displays the time from the phone, doesn't care about timezone or DST or anything like that).

A cleaner solution would be to have a companion app. I forked the code with the intention of doing something like that but haven't had the time to actually start unfortunately.

**Comment by jsquyres** [comment]
@Dazby Good comments; thanks.

Would Alarm++ _need_ to know the difference?  If Pebble OS doesn't have notification to apps when the time changes, a super-crude-but-possibly-effective solution would be to wake up Alarm++ once a minute (or whatever frequency doesn't eat up too much battery?) and simply recalculate the actual time of the first active alarm.  If the newly-computed time of the alarm doesn't match the previously-computed time of the alarm, you can then know "Ah ha -- something big happened; I need to re-compute all active alarms."

**Comment by reini1305** [comment]
@jsquyres Hey! Great that we have this discussion here. If the OS would notify my app on a time change (which it doesn't) I could easily reschedule the alarms. 

@Dazby Adding a listener to the HOUR doesn't help either because the app is not always in the foreground. So I could write a background worker for that, but that seems like overkill for such a rare event as changing timezones.

Another possibility would be to wake up once an hour, update the alarms and exit the app immediately. This would cost one alarm slot though.
EDIT: @jsquyres you were faster with that idea

**Comment by Dazby** [comment]
True, I was just throwing ideas out there. Roll on Pebble Timeline!

How about using the timer to run an ApptimerCallback every x hours, passing in the struct_tm of the last time the function was called when rescheduling. Then when the callback is run, get the current struct_tm and compare the hour values. If they're not x hours apart then reschedule the alarms? The timer could run twice a day (x=12) instead of every hour etc. This is assuming that localtime returns the time relevant to that time zone of course.

One edge case I can think of is what happens when if the watch is off when the timer expires. I won't be able to code this up today but could possibly look at it at the weekend

**Comment by jsquyres** [comment]
Sorry for the delay in reply -- as noted in my original comment, I'm on a business trip this week (that has been all-consuming, yow!).

Yeah, checking every hour (or every X frequency) does seem a bit overkill.  If only there was some way to _know_.  Bummer.

I guess there's two main ideas being discussed here:
1. How to wake up an invoke a "check the alarms" event.  Options including running at X frequency (e.g., once an hour), but waking up on some kind of event would be awesome, too (e.g., when time gets adjusted -- but it doesn't look like that is a possibility).  FWIW, running at X frequency wouldn't be sexy, and it may be a little overkill, but if it doesn't take too much battery, it may well be a solid/reliable mechanism.
2. What to do when waking up.  I haven't had a chance to look at the code -- when you program the alarm, are you telling Pebble OS when to wake you up, and then you have no control / no way to query the settings of the alarm you programmed?

Another thought that is somewhat the combination of those two: this could be a bastardized version of event-based programming (and again, I know nothing about Pebble OS, so forgive me if this is stupid!).  Do something like this:

``` c
void when_Alarm++_is_in_foreground() { set_next_alarm() }

void when_Alarm++_goes_to_background() { set_next_alarm() }

void set_next_alarm() {
  e = find_next_alarm(); // finds next Alarm++ alarm to go off

  // arbitrarily choose 1 hour for this example; can set it to whatever frequency makes sense
  if (e > 1_hour_from_now) { 
    e = make_event(1_hour_from_now); 
  }

  set_pebble_os_alarm(e, alarm_callback);
}

void alarm_callback() {
  gettimeofday(&tm);
  // If we were fired because it's actually time to sound an alarm, then do so
  if (find_alarm(tm, &a)) {
    sound_alarm(a);
  }
  set_next_alarm();
}
```

**Comment by reini1305** [comment]
When the app wakes up it searches for the alarm which caused the wakeup (I get that info from the OS). Then I do the ringing and stuff, and finally I'm rescheduling this single alarm for the next time (may it be that the user hit snooze or to make sure it rings on the next day). Then the app exits. When you start the app via the menu, all alarms are rescheduled on exit.

So in essence, I'm already doing what your code snipped suggests, except that I use  one wakeup call per alarm (pebble allows 8 calls, so 8 alarms). I would only have to find out which alarm rings next, but this would be a major rewrite of the wakeup code ;) Then I could use one wakeup call for maintainance and a second one for the actual alarm. This would also remove the silly 8 alarm limit...

**Comment by jsquyres** [comment]
@reini1305 Meaning: I really should look at the code before making a "suggestion." :-)

**Comment by reini1305** [comment]
@jsquyres @Dazby I think I might have solved the problem now. I've implemented a background task which wakes up once an hour and checks how much time has passed. If the time is off more than 10 seconds, the alarms are rescheduled. This should work against the DST as well as the timezone problem. I will upload a new version later this day.

**Comment by jsquyres** [comment]
Oh, sweet!

I had finally gotten around to learning about the Pebble API and writing a
few watchfaces (e.g., https://github.com/jsquyres/pebble-sorta), and was
just about to set my sights on Alarm++ this week (it's spring break -- a
great time for hobby coding!).  But hey, if it's already fixed, that's
fantastic -- thank you!

On Mon, Apr 6, 2015 at 6:51 AM, Christian Reinbacher <
notifications@github.com> wrote:

> @jsquyres https://github.com/jsquyres @Dazby https://github.com/Dazby
> I think I might have solved the problem now. I've implemented a background
> task which wakes up once an hour and checks how much time has passed. If
> the time is off more than 10 seconds, the alarms are rescheduled. This
> should work against the DST as well as the timezone problem. I will upload
> a new version later this day.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/reini1305/alarmsplusplus/issues/3#issuecomment-90015411
> .

## 

{+} Jeff Squyres
