### ISSUE TITLE
Make Descriptions Longer

### ISSUE THREAD

**Issue by darrylmendonez** [reini1305/alarmsplusplus#8]
The description character length is too short. Could you make it longer?

**Comment by reini1305** [comment]
Technically yes, practically not that easily because I'm running out of memory on classical pebbles. Maybe I will build a separate version for newer Pebbles since this is an often requested feature
Am 20.05.2016 18:08 schrieb Darryl Mendonez notifications@github.com:The description character length is too short. Could you make it longer?

**Comment by reini1305** [comment]
Fixed in today's commit!
